### ISSUE TITLE
Incorporate kaomoji database from Peachy

### ISSUE THREAD

**Issue by andrew222651** [iansinnott/asciilib#1]
There are a bunch of kaomojis here with tags:
https://github.com/itsmeichigo/peachy/blob/main/Peachy/kaomoji.json
But they don't have names so I'm not sure how you'd want to deal with that. Maybe concatenate the tags with a counter like `whatever_shrug_1`, `whatever_shrug_2`.

**Comment by andrew222651** [comment]
I'd be happy to submit a PR

**Comment by iansinnott** [comment]
yeah that would be great. PRs definitely welcome. Agreed re: the tags, that seems like the most reasonable approach to generating searchable names.
